### ISSUE TITLE
Decide whether to encourage (and demonstrate) use of capsule in non-PAAS environments

### ISSUE THREAD

**Issue by GalateaRaj** [galatea-associates/fuse-starter-java#11]

**Comment by GalateaEric** [comment]
Raj believes there is a standing decision to be made of whether we are still proponents of capsule any longer.

**Comment by mikegajda** [comment]
Startup scripts? Docker? etc. Need to investigate what recommendations we want to make.

**Comment by mikegajda** [comment]
This appears to already be decisioned in: https://github.com/galatea-associates/fuse-starter-java/issues/226

I do think there is an open question of how containers should fit in to Fuse. My recommendation is that a new ticket is opened to add a Dockerfile for building images to run on non-CloudFoundry environments as examples of this will be required going forward as Kubernetes-based deployments become more popular.

**Comment by mikegajda** [comment]
Thoughts from Steerco: use Spring uber jars to replace capsule. Have a start script to lock in command line params. Thoughts on Docker would be that it's not worth the time yet as likely not usable in our environments yet.
