### ISSUE TITLE
Integrate with spring metrics

### ISSUE THREAD

**Issue by GalateaRaj** [galatea-associates/fuse-starter-java#28]
Figure out what we want to do here.

Also figure out how we would export metrics to a collector (e.g. statsd or collectd).

**Comment by GalateaRaj** [comment]
I should add that performance metrics should integrate with our tracer so that we have a consolidated view of metrics and a trace that we can store in our trace repository.

**Comment by GalateaRaj** [comment]
Also worth looking at dropwizard metrics to see if we want to use that instead

**Comment by mikegajda** [comment]
Would like to close pending review by SteerCo

**Comment by mikegajda** [comment]
SteerCo: duplicate, will close
