### ISSUE TITLE
Demonstrate @async annotation 

### ISSUE THREAD

**Issue by GalateaRaj** [galatea-associates/fuse-starter-java#35]
Demonstrate the following:
- How to return a callable as well as a void
- How to use your own executor (instead of the default one)

**Comment by GalateaRaj** [comment]
Some sample configuration:

@Configuration
@EnableAsync
public class AppConfig implements AsyncConfigurer {

    @Override
    public Executor getAsyncExecutor() {
        return null; //Use default behavior.
/*         ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(7);
        executor.setMaxPoolSize(42);
        executor.setQueueCapacity(11);
        executor.setThreadNamePrefix("MyExecutor-");
        executor.initialize();
        return executor; */
    }

    @Override
    public AsyncUncaughtExceptionHandler getAsyncUncaughtExceptionHandler() {
        return MyAsyncUncaughtExceptionHandler();
    }
}

**Comment by gala-dan** [comment]
Interesting blog post about the use of Future<> and CompletableFuture<> when dealing with @Async methods.

http://javapapo.blogspot.co.uk/2016/04/spring-async-and-javas-8.html

**Comment by GalateaEric** [comment]
DECISION NEEDED: the crux of the desired decision is what use case to demonstrate the @async...

**Comment by GalateaEric** [comment]
revisit later, may be demoted in favor of a broader task on asynchronicity in general.

**Comment by mikegajda** [comment]
New projects, use Webflux or Reactor framework. If an old project, @async might still be useful, but we won't show it here.
