### ISSUE TITLE
Document Tracer

### ISSUE THREAD

**Issue by j-barber** [galatea-associates/fuse-starter-java#55]
What is Tracer.java used/useful for? What does it do?

**Comment by paulo-reichert** [comment]
Tracer.java is not used anywhere in Fuse. FuseWebRequestTraceFilter is used for web requests tracing. Should this class be deleted?

**Comment by Gala-Sortino** [comment]
@GalateaRaj this still says decision needed, is this still the case or has a decision be made so I can go ahead and delete the file?

**Comment by Gala-Sortino** [comment]
> Tracer.java is not used anywhere in Fuse. FuseWebRequestTraceFilter is used for web requests tracing. Should this class be deleted?

The tracer class is invoked from within the FuseWebRequestTraceFilter, as it calls "runAndTraceSuccess" which is a method inside of Tracer.java

**Comment by GalateaEric** [comment]
Documentation and class are both required.  Please add an interesting javadoc to the class.

Attempt to refer to Raj (the original author) if we need more input on what this thing does.

**Comment by mikegajda** [comment]
I believe Tracer has been decommissioned, so I think this should be closed as st:won't fix. Moving back to st:decision-needed

**Comment by mikegajda** [comment]
Tracer has been removed since it's not compatible w/ Spring 2.
