### ISSUE TITLE
Fix log files getting created twice at Application Startup

### ISSUE THREAD

**Issue by ConorEbbs** [galatea-associates/fuse-starter-java#77]
All log files get created on application startup, the only thing that gets logged out is:

2017.09.14 11:29:58.169 [main] INFO  o.g.s.Application - Starting spring application fuse-starter-java

Then the logger seems to roll and create a whole new set of log files.

The log files have the same formatting, so it doesn't seem to be the default logging getting started before finding the log4j2 setup.

![image](https://user-images.githubusercontent.com/22845358/30438933-7f898ad6-9940-11e7-8c08-c05b5216dcfd.png)

**Comment by gala-lightfoot** [comment]
This isn't an issue as such.  Our log file prefix uses the date format: _yyyyMMddHHmm**ss**_, which as a result writes to a new log file every second.  I'll get this changed to do it on an hourly basis.

**Comment by paulo-reichert** [comment]
The issue doesn't seem to appear on my machine with the latest version of the code in develop:
![image](https://user-images.githubusercontent.com/13468907/36730749-8a4eb6a2-1b96-11e8-97f2-684a927d708e.png)

This is as of commit d1f90a9868661e302ad39ca730c84e7e21b194cb.

**Comment by gala-lightfoot** [comment]
It doesn't happen reliably.  Start/stop the app a couple more times and I imagine you'll see the behaviour above.

**Comment by GalateaRaj** [comment]
Is this less of an issue since we are going 12-factor (which says that we should log to stdout)?

**Comment by j-barber** [comment]
Many of the apps we develop will still want/need to log to a filesystem (rather than ELK-like stack or Splunk), right? If so, worth leaving the config as an illustrative example?

**Comment by paulo-reichert** [comment]
I think we should show both options as I agree with @j-barber that most apps we deal with will still require file-based logging.

**Comment by gala-lightfoot** [comment]
I put Log4j into debug mode and pulled out some of the logs to see what's going on under the hood.

> 2018-03-02 14:16:17,158 main DEBUG Shutting down RollingFileManager ${sys:application.log-dir}/20180302141616.${sys:application.name}.warnings.log
> 2018-03-02 14:16:17,158 main DEBUG Shut down RollingFileManager ${sys:application.log-dir}/20180302141616.${sys:application.name}.warnings.log, all resources released: true
> 2018-03-02 14:16:17,159 main DEBUG Shutting down RollingFileManager ${sys:application.log-dir}/20180302141616.${sys:application.name}.log
> 2018-03-02 14:16:17,159 main DEBUG Shut down RollingFileManager ${sys:application.log-dir}/20180302141616.${sys:application.name}.log, all resources released: true
> 2018-03-02 14:16:17,159 main DEBUG Shutting down RollingFileManager ${sys:application.log-dir}/20180302141616.${sys:application.name}.rest.log
> 2018-03-02 14:16:17,159 main DEBUG Shut down RollingFileManager ${sys:application.log-dir}/20180302141616.${sys:application.name}.rest.log, all resources released: true
> 2018-03-02 14:16:17,159 main DEBUG Shutting down RollingFileManager ${sys:application.log-dir}/20180302141616.${sys:application.name}.errors.log
> 2018-03-02 14:16:17,159 main DEBUG Shut down RollingFileManager ${sys:application.log-dir}/20180302141616.${sys:application.name}.errors.log, all resources released: true

On the occasions we get **two** sets of log files from startup, the above snippet is seen. It shows the RollingFileManager shutting down for each newly created log file (before Spring has started).  I assume this shutdown forces new log files to be created (with a new file name, hence the second set of logs).

On startup, when the logging functions as expected (only one set of logs), the shutdown (seen above) of the RollingFileManager is not present in the logs.  As to why this happens, the logs provide no insight.

**Comment by paulo-reichert** [comment]
I'll close this given the change to 12-factor and the difficulty to replicate and diagnose.

**Comment by ewingalatea** [comment]
I ran into this same issue when working with log4j2 in my client work. 
James and I found a fix. 
I will attempt to raise a PR to put the fix into Fuse

**Comment by j-barber** [comment]
See http://apache-logging.6191.n7.nabble.com/log4j2-creates-empty-log-file-when-configuration-happens-td72113.html and https://issues.apache.org/jira/browse/LOG4J2-1504 for reference.

**Comment by GalateaEbbs** [comment]
Currently we are creating 3 application log files on startup, because there are three events during Spring Boot initialization which usually happen about a second apart which create new log files since the log file name below is formatted with seconds (HHmmss). We COULD mask this by removing seconds from this config, but it would still create multiple files if the JVM was started right as the minute changes. Not a big deal so we're leaving it for now.

**Comment by GalateaEric** [comment]
we are merging the PR that addresses some aspects of this issue, but leaving the issue open as it's technically not yet fully solved.  The issue may in fact not truly be solvable.  Let's not spend too much more time working on this one as it's pretty benign.

**Comment by GalateaEric** [comment]
This is done, PR merged.
